### ISSUE TITLE
Error Caused by: java.lang.OutOfMemoryError: Map failed 	at sun.nio.ch.FileChannelImpl.map0(Native Method)

### ISSUE THREAD

**Issue by har2121** [meerkatzenwildschein/jeboorker#13]
While updating my books (I've many books) in Jeboorker I had the following error:

Caused by: java.lang.OutOfMemoryError: Map failed
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	... 28 more

I don't know anything on programming, but I searched for some solutions, and I've found the two in the attached files.

Can you look at this error?

Ys. Harry
[FireShot Screen Capture #409 - 'Error java_io_IOException_ Map failed and java_lang_OutOfMemoryError_ Map failed appears in DNG' - www_ibm_com.pdf](https://github.com/meerkatzenwildschein/jeboorker/files/6095768/FireShot.Screen.Capture.409.-.Error.java_io_IOException_.Map.failed.and.java_lang_OutOfMemoryError_.Map.failed.appears.in.DNG.-.www_ibm_com.pdf)

[FireShot Screen Capture #409 - 'Error java_io_IOException_ Map failed and java_lang_OutOfMemoryError_ Map failed appears in DNG' - www_ibm_com.pdf](https://github.com/meerkatzenwildschein/jeboorker/files/6095765/FireShot.Screen.Capture.409.-.Error.java_io_IOException_.Map.failed.and.java_lang_OutOfMemoryError_.Map.failed.appears.in.DNG.-.www_ibm_com.pdf)

**Comment by meerkatzenwildschein** [comment]
Hello Harry,

if you have other parts of the error message, it would be helpful if you could write them here as well, to better narrow down the specific error. Perhaps you also have very large e-book files that need to be read in? Likewise, if you have a lot of books, the database with the meta data also needs more memory.

You can allow Jeboorker to use more memory if you customize the script file with the program call.On Windows you can find it under the name Jeboorker.vbs in the Jeboorker installation directory. On Debian/Ubuntu the script file is located under /usr/share/jeboorker/jeboorker.sh.

Please change the call parameter -Xmx512m to -Xmx2048m. If this is still not sufficient, you can configure the value even higher.This value represents the amount of memory in megabytes that Jeboorker is allowed to use.

I hope I could help.

Many greetings

**Comment by har2121** [comment]
Hello,

I've changed the amount of memory to 4096 (see attachment), but Jeboorker shuts down itself again before finishing refreshing the folder. In the attachment a part of the three logs I've saved. I saw after the first two logs that Jeboorker stopped at one particular file. I've removed this file and run Jeboorker again. Now it stops on another file (see third log).

I hope you can do something with this information.
[Part 1.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6097296/Part.1.txt)
[Log 2.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6097297/Log.2.txt)
[Part 3.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6097298/Part.3.txt)





[Jeboorker.vbs.log](https://github.com/meerkatzenwildschein/jeboorker/files/6097140/Jeboorker.vbs.log)

**Comment by meerkatzenwildschein** [comment]
Hi, thank you for the insightful logfiles. Indeed, it seems that a significant amount of memory is used in one piece when reading a PDF file. The -Xmx parameter cannot help here. It seems to be advisable to use a different mechanism for reading in PDF files of a certain size, which is however less performant. 

Can you tell me the approximate size in megabytes of the PDF files you want to read?

See also https://stackoverflow.com/questions/23132009/java-large-file-upload-throws-java-io-ioexception-map-failed

**Comment by meerkatzenwildschein** [comment]
The technical problem is described here https://stackoverflow.com/questions/23132009/java-large-file-upload-throws-java-io-ioexception-map-failed

**Comment by har2121** [comment]
I've looked at the size of PDF files. The biggest file is 655.024.618 bytes. This file however passed the Refresh folder. I can see en open it in Jeboorker. The file 'Consumentengids 2020 Nr 03 Mrt.pdf' is 82.970.053 bytes, so the filesize seems not the problem. Maybe something in the file itself is the problem? I tried to attach this file for you, but it is to big.

I see now that you have a new version of Jeboorker released. I wil try it and report if it solved the problem or not.

**Comment by meerkatzenwildschein** [comment]
In fact, it is not only about the size of the file in memory, but unfragmented memory is required for the entire file. I have set the threshold here to 100MB. 

You can configure the value by adding another entry in the preference file at  (user home).java/.userPrefs/jeboorker/prefs.xml. The entry must be under the map element.

` <entry key="pdf.random_access.threshold.mb" value="1"/>
`

**Comment by har2121** [comment]
I've changed the vbs file to 4096 and tried to run the Refresh folder. Unfortunately Jeboorker shuts down and in the log file I saw that it is the same file (Consumentengids 2020 Nr 03 Mrt.pdf). I use Windows 10 pro. I could not find the (user home).java/.userPrefs/jeboorker/prefs.xml file (I searched with Everything and started it als Admin). Where can I find this file?

**Comment by meerkatzenwildschein** [comment]
Apparently Java on Windows uses the registry for its preferences. Only under Linux there is the file prefs.xml.

HKEY_CURRENT_USER\Software\JavaSoft\Prefs\jeboorker

I'll build and upload a new version 1.2.9 right away that doesn't use the memory critical mechanism anymore. Then you don't need to configure anything anymore.

**Comment by har2121** [comment]
I've used an other useraccount and started Jeboorker. Jeboorker was empty. I've added the folder and Jebooker shuts down again, but on another file. This file passed well with the earlier useraccount. The file is 137.229.770 bytes big and is named "Consumentengids - 07 08 juli-aug 2010.pdf". Than I moved the whole folder with the files of Consumentengids to another folder and Refreshed folder. Now it was succesful. Than I moved the whole folder to the Dummy folder and Refreshed the Dummy folder within Jeboorker. Jeboorker shuts down immediately. So it has to do something with these files.

**Comment by har2121** [comment]
I was forgotten to mention that I use Jeboorker 1.2.9

**Comment by har2121** [comment]
I saw in the Jeboorker.bat file, that I use to start Jeboorker, the same memory statement that is used in the Jeboorker.vbs file. I've changed in the .bat file 512 in 4096, but than Jeboorker doesn't start anymore.

**Comment by har2121** [comment]
1024 in the .bat file works!

**Comment by meerkatzenwildschein** [comment]
Sounds very strange. Can you please provide me a logfile with the OutOfMemory-Error that was caused by version 1.2.9? 

Can you please also send me the data from the beginning of the log file that is logged first after starting the application? This is system information that might give some insight.

**Comment by meerkatzenwildschein** [comment]
You can also try to increase the memory for the mapping. For this you can add the following parameter to the Xmx parameter: `-XX:MaxDirectMemorySize=2g`

https://javarevisited.blogspot.com/2014/11/javaioioexception-map-failed-javalangoutofmemoryerror.html

**Comment by har2121** [comment]
See atachments.
[Log end.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6110788/Log.end.txt)
[Java version.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6110791/Java.version.txt)
[Log begin.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6110805/Log.begin.txt)

**Comment by meerkatzenwildschein** [comment]
The last message has changed a bit which is a good thing. `Java heap space` can be fixed with the increased Xmx-Parameter. Looks like the change in the vbs file was reverted by the installation of version 1.2.9. Please set -Xmx4096m in the vbs file again and retry.

It may also be a good idea to change to a 64 bit version of java. The log file says `os.arch=x86`, which indicates that a 32-bit version of Java is installed. The value of a 64-bit version is `amd64`. Running a 64 bit Java version allowing it to map more memory. You may uninstall the 32 bit version of java and install a 64 bit one instead.

**Comment by har2121** [comment]
FYI attached the config files


[Jeboorker.vbs.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6111136/Jeboorker.vbs.txt)
[Jeboorker.bat.txt](https://github.com/meerkatzenwildschein/jeboorker/files/6111137/Jeboorker.bat.txt)

**Comment by meerkatzenwildschein** [comment]
The bat file is not that important. If you click the exe file it tries to start the Jeboorker.vbs file. You can also directly start with the Jeboorker.vbs file. Where does the file extension .txt comes from? Maybe after editing the file with notepad? Please take sure that the start parameter in the first line of the logfile matches to the parameters in the vbs file.

**Comment by har2121** [comment]
Yes, I use the 32-bit version of Java. I will try to replace it with a 64-bit version. Thank you for the good work!

**Comment by meerkatzenwildschein** [comment]
You're welcome, I hope it will help.
