### ISSUE TITLE
Installation openSUSE

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [meerkatzenwildschein/jeboorker#3]
Hi, I'm tring to install Jebooker in openSUSE. I donwloaded the tar.gz and I found just the jeboorker.sh to try something. Is it?

```
using java binary /usr/bin/java
starting with classpath lib/annotations-3.0.0.jar:lib/ant-1.7.0.jar:lib/ant-launcher-1.7.0.jar:lib/bcpkix-jdk15on-1.52.jar:lib/bcprov-ext-jdk15on-1.52.jar:lib/bcprov-jdk15on-1.52.jar:lib/bounce-0.19_1.jar:lib/commons-1.0.jar:lib/commons-codec-1.6.jar:lib/commons-collections4-4.1.jar:lib/commons-compress-1.4.1.jar:lib/commons-exec-1.3.jar:lib/commons-io-2.4.jar:lib/commons-lang-2.6.jar:lib/commons-lang3-3.4.jar:lib/commons-lang3-3.5.jar:lib/commons-logging-1.0.4.jar:lib/commons-logging-1.1.3.jar:lib/commons-net-2.2.jar:lib/commons-swing-1.0.jar:lib/commons.swing-1.0.jar:lib/commons-vfs-1.0.jar:lib/dropbox-core-sdk-1.7.7.jar:lib/epublib-3.1.jar:lib/gson-2.3.1.jar:lib/h2-1.4.193.jar:lib/htmlcleaner-2.2.jar:lib/httpclient-4.3.3.jar:lib/httpcore-4.3.2.jar:lib/httpmime-4.3.3.jar:lib/itext-5.jar:lib/jackson-core-2.4.0-rc3.jar:lib/javax.websocket-api-1.1.jar:lib/jcl-over-slf4j-1.7.7.jar:lib/jdom-1.1.jar:lib/jeboorker-main-1.2.3.jar:lib/jempbox-0.2.0_1.jar:lib/jgoodies-common-1.7.0.jar:lib/jgoodies-looks-2.5.3.jar:lib/jmupdf-0.5.0.jar:lib/jna-3.4.0.jar:lib/jpushbullet2-0.3.0-SNAPSHOT.jar:lib/jsoup-1.8.1.jar:lib/junique-1.0.4.jar:lib/junit-3.8.1.jar:lib/jxlayer-3.0.4.jar:lib/kxml2-2.3.0.jar:lib/l2fprod-7.3_1.jar:lib/miglayout-3.7.4.jar:lib/miglayout-core-5.0.jar:lib/miglayout-swing-5.0.jar:lib/mobi-api4java-0.0.2-SNAPSHOT.jar:lib/myswing-1.0.jar:lib/ormlite-core-5.0.jar:lib/ormlite-jdbc-5.0.jar:lib/platform-3.4.0.jar:lib/slf4j-api-1.7.7.jar:lib/truezip-driver-file-7.7.10.jar:lib/truezip-driver-zip-7.7.10.jar:lib/truezip-file-7.7.10.jar:lib/truezip-kernel-7.7.10.jar:lib/truezip-swing-7.7.10.jar:lib/weblaf-1.29.jar:lib/xmlpull-1.1.3.4d_b4_min.jar:lib/xz-1.0.jar:
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
Jeboorker 1.2.3 started with -Xmx512m -XX:+UseParNewGC -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 -XX:+AggressiveOpts
java.runtime.name=OpenJDK Runtime Environment
sun.boot.library.path=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/amd64
java.vm.version=25.131-b11
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=OpenJDK 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=BR
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/home/viniciusbr/Downloads/jeboorker_1.2.3/jeboorker
java.runtime.version=1.8.0_131-b11
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.endorsed.dirs=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/endorsed
os.arch=amd64
java.io.tmpdir=/tmp
line.separator=

java.vm.specification.vendor=Oracle Corporation
os.name=Linux
sun.jnu.encoding=UTF-8
java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=4.4.70-18.9-default
user.home=/root
user.timezone=Europe/Copenhagen
java.awt.printerjob=sun.print.PSPrinterJob
file.encoding=UTF-8
java.specification.version=1.8
java.class.path=lib/annotations-3.0.0.jar:lib/ant-1.7.0.jar:lib/ant-launcher-1.7.0.jar:lib/bcpkix-jdk15on-1.52.jar:lib/bcprov-ext-jdk15on-1.52.jar:lib/bcprov-jdk15on-1.52.jar:lib/bounce-0.19_1.jar:lib/commons-1.0.jar:lib/commons-codec-1.6.jar:lib/commons-collections4-4.1.jar:lib/commons-compress-1.4.1.jar:lib/commons-exec-1.3.jar:lib/commons-io-2.4.jar:lib/commons-lang-2.6.jar:lib/commons-lang3-3.4.jar:lib/commons-lang3-3.5.jar:lib/commons-logging-1.0.4.jar:lib/commons-logging-1.1.3.jar:lib/commons-net-2.2.jar:lib/commons-swing-1.0.jar:lib/commons.swing-1.0.jar:lib/commons-vfs-1.0.jar:lib/dropbox-core-sdk-1.7.7.jar:lib/epublib-3.1.jar:lib/gson-2.3.1.jar:lib/h2-1.4.193.jar:lib/htmlcleaner-2.2.jar:lib/httpclient-4.3.3.jar:lib/httpcore-4.3.2.jar:lib/httpmime-4.3.3.jar:lib/itext-5.jar:lib/jackson-core-2.4.0-rc3.jar:lib/javax.websocket-api-1.1.jar:lib/jcl-over-slf4j-1.7.7.jar:lib/jdom-1.1.jar:lib/jeboorker-main-1.2.3.jar:lib/jempbox-0.2.0_1.jar:lib/jgoodies-common-1.7.0.jar:lib/jgoodies-looks-2.5.3.jar:lib/jmupdf-0.5.0.jar:lib/jna-3.4.0.jar:lib/jpushbullet2-0.3.0-SNAPSHOT.jar:lib/jsoup-1.8.1.jar:lib/junique-1.0.4.jar:lib/junit-3.8.1.jar:lib/jxlayer-3.0.4.jar:lib/kxml2-2.3.0.jar:lib/l2fprod-7.3_1.jar:lib/miglayout-3.7.4.jar:lib/miglayout-core-5.0.jar:lib/miglayout-swing-5.0.jar:lib/mobi-api4java-0.0.2-SNAPSHOT.jar:lib/myswing-1.0.jar:lib/ormlite-core-5.0.jar:lib/ormlite-jdbc-5.0.jar:lib/platform-3.4.0.jar:lib/slf4j-api-1.7.7.jar:lib/truezip-driver-file-7.7.10.jar:lib/truezip-driver-zip-7.7.10.jar:lib/truezip-file-7.7.10.jar:lib/truezip-kernel-7.7.10.jar:lib/truezip-swing-7.7.10.jar:lib/weblaf-1.29.jar:lib/xmlpull-1.1.3.4d_b4_min.jar:lib/xz-1.0.jar:
user.name=root
java.vm.specification.version=1.8
sun.java.command=org.rr.jeborker.Jeboorker
java.home=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre
sun.arch.data.model=64
user.language=pt
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_131
java.ext.dirs=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path=/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/resources.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/rt.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/sunrsasign.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/jsse.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/jce.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/charsets.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/jfr.jar:/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/classes
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
sun.cpu.isalist=
Startup failed.
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.setDynamicLayout(HeadlessToolkit.java:294)
	at org.rr.jeborker.gui.MainController.initialize(MainController.java:147)
	at org.rr.jeborker.gui.MainController.getController(MainController.java:79)
	at org.rr.jeborker.Jeboorker.main(Jeboorker.java:74)
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
	at org.rr.jeborker.Jeboorker.closeSplashScreen(Jeboorker.java:117)
	at org.rr.jeborker.Jeboorker.main(Jeboorker.java:85)
```

**Comment by meerkatzenwildschein** [comment]
Hi, looks like there something with your display environment variable. Please take a look at the following link. https://stackoverflow.com/questions/662421/no-x11-display-variable-what-does-it-mean

**Comment by ViniciusBRodrigues** [comment]
Hi,
I have installed putty to solve that, but the "Enable X11 forwarding" is nothing working in my system. Thank you!

**Comment by meerkatzenwildschein** [comment]
My pleasure! :-)
