### ISSUE TITLE
Convert CBR -> CBZ sporadically fails with Exception

### ISSUE THREAD

**Issue by meerkatzenwildschein** [meerkatzenwildschein/jeboorker#5]
Convert CBR -> CBZ sporadically fails with the following Exception. Conversion Error must not end in an invalid file.

24.05.2018 19:41:11 SEVERE: Could not create script.
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@73c2bace rejected from java.util.concurrent.ThreadPoolExecutor@77fd306e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681)
	at org.rr.commons.utils.ProcessExecutor.makeExecutable(ProcessExecutor.java:112)
	at org.rr.commons.utils.ProcessExecutor.createLinuxCommandLineScript(ProcessExecutor.java:97)
	at org.rr.commons.utils.ProcessExecutor.createCommandLineScript(ProcessExecutor.java:65)
	at org.rr.commons.utils.ProcessExecutor.runProcessAsScript(ProcessExecutor.java:41)
	at org.rr.commons.utils.compression.rar.LazyRarDataEntry.getBytes(LazyRarDataEntry.java:43)
	at org.rr.jeborker.converter.AArchiveToArchiveConverter$1.run(AArchiveToArchiveConverter.java:83)
	at org.rr.jeborker.converter.AArchiveToArchiveConverter$1.run(AArchiveToArchiveConverter.java:78)
	at org.rr.commons.utils.ThreadUtils$1.run(ThreadUtils.java:66)
	at java.lang.Thread.run(Thread.java:748)
24.05.2018 19:41:11 SEVERE: To list files in rar /home/guru/E-Books/Mangas/Aqua/Aqua (Tokyopop 2011)_1.cbr
java.util.concurrent.ExecutionException: Failed to execute [/usr/bin/unrar, e, -n"313.jpg", -o+, "/home/guru/E-Books/Mangas/Aqua/Aqua_1.cbr", /tmp/62001883-c61b-4a48-afc6-dc64bb349225]
	at org.rr.commons.utils.ProcessExecutor.createLinuxCommandLineScript(ProcessExecutor.java:104)
	at org.rr.commons.utils.ProcessExecutor.createCommandLineScript(ProcessExecutor.java:65)
	at org.rr.commons.utils.ProcessExecutor.runProcessAsScript(ProcessExecutor.java:41)
	at org.rr.commons.utils.compression.rar.LazyRarDataEntry.getBytes(LazyRarDataEntry.java:43)
	at org.rr.jeborker.converter.AArchiveToArchiveConverter$1.run(AArchiveToArchiveConverter.java:83)
	at org.rr.jeborker.converter.AArchiveToArchiveConverter$1.run(AArchiveToArchiveConverter.java:78)
	at org.rr.commons.utils.ThreadUtils$1.run(ThreadUtils.java:66)
	at java.lang.Thread.run(Thread.java:748)
24.05.2018 19:41:11 SEVERE: Failed to convert file 313.jpg
java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
	at org.rr.jeborker.converter.AArchiveToArchiveConverter$1.run(AArchiveToArchiveConverter.java:86)
	at org.rr.jeborker.converter.AArchiveToArchiveConverter$1.run(AArchiveToArchiveConverter.java:78)
	at org.rr.commons.utils.ThreadUtils$1.run(ThreadUtils.java:66)
	at java.lang.Thread.run(Thread.java:748)

**Comment by meerkatzenwildschein** [comment]
Commit fe5dc040e9ffb06063c68ec86d85fb25f7322835 Fix Issue #5 and optimize Thread handling in Process cexecution
